# Site
name: Jonathan Rodgers
description: Just another website
meta_description: Just another website
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'hello@john.doe'
google_analytics:
disqus:
sharethis:

# Authors
authors:
  john:
    name: Jonathan Rodgers
    display_name: Jonathan Rodgers
    image: /assets/images/home.jpg
    email: rodgersjonathan11@outlook.com
    web: example.com
    twitter:
    description: Hi, I am Jonathan Rodgers

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: john
  card: summary

facebook:
  app_id:
  publisher: john.com
  admins:

social:
name: John Doe
links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://github.com/
